### PR TITLE
v2 - Backup Mode & Edit Start Time

### LINKED ISSUE #30: Add Version Number to Home Page
Perhaps a small Version X.Y below the Start Guide Button

### LINKED ISSUE #31: Add Race Name to Support Request Email Subject
Could we add the race name to the email subject?

image

For instance, when we get a ticket from RaceDay Scoring it is formatted like this:

`{race_name} RaceDay Scoring Support Incident`

I like showing the name of the Race before the mobile timing app part of the subject

### LINKED ISSUE #35: Add capability to edit existing or enter timestamp of start time
The use case is a timer started the race too soon and needs to quickly change it on the fly, or they recorded a time stamp of the start from another source and need to manually set the time.

I think offering a way to tap the start time field that would open up a modal to allow you to enter the start time of day could accomplish this.

### LINKED ISSUE #39: Backup App Mode
We will support a third mode, in addition to Online Races and Offline Events. This third "Backup Mode" will allow the user to sync down participant information and bib numbers (so that they can see participant names in Results Mode and use the Grid View in Finish Line Mode), but it will never sync any information up to RSU. The only way users will be able to get information out of this mode is to export it themselves. As part of this update, we will add support for periodic syncing of Bib Numbers when in Grid View.

### LINKED ISSUE #44: Warn User of Multiple Result Sets
Warn the user if there are multiple result sets on the Mode Screen. Don't allow entry into any of the modes.

### LINKED ISSUE #46: Style Fixes
- [x] Vertical Scrollbars
- [x] Table Headers
- [x] Finish Line Mode Loading
- [x] Icon Updates

### LINKED ISSUE #48: Fix iOS App Name
I think the name on iOS is too long on the Home Screen. Can this be fixed?
IMG_3943

### LINKED ISSUE #50: v2 Review - Assign Offline Event Bug
We're not sure exactly what caused Chelsea to get into this state, but she had an Offline Event with this Records structure:
`[[1, X, 1], [2, X, 2], [3, X, 3], [4, X, 0], [5, X, 0], [6, X, 0], etc.]`

When assigning that offline event, the Checker Bibs were being selected instead of the Bib Numbers, so the Online Event ended up with this only three bibs.

We should make sure that we aren't having unnecessary zeroes in Offline Results Mode, but more importantly, we need to fix our Assign Event logic to grab the better set of data.

### LINKED ISSUE #51: v2 Review - Chute Mode Bibs Not Pushed
Major bug @chelseaRSU found. When we saved in Finish Line Mode, we were pushing checker bibs whether or not they were all 0s. Then, when we saved in Chute Mode, if there were results at RSU (which there were, as an array of 0s), we didn't push anything to RSU. So basically, the normal flow of Finish Line Mode and then Chute Mode was broken, unless the user made an edit in Results and re-pushed the correct data to RSU. This has been here since v1 and somehow we missed it.

### LINKED ISSUE #52: v2 Review - Unnecessary `start_time` Field
We are storing an unnecessary `start_time` field on the OfflineEvent object.

### LINKED ISSUE #56: v2 Review - Edit Start Time / Time Entry Bugs
1. Time Entry Bib Bug (Steps to Reproduce):
- Open Results Mode in an event
- Delete all results (just to give yourself a clean slate)
- Add two records in edit mode
- Tap the bib on record 1 to edit it
- Change the bib from 0 to any real number
- Hit next
- The time has changed correctly to the time for place 2, but the bib has not changed to 0

2. Time Entry Time Bug (Steps to Reproduce):
- Open Results Mode in an event
- Delete all results
- Add a record in edit mode (the time should display as `00:00:00.01` in the results list)
- Tap the time to edit it
- The time entry field will show `00:00:00.10` instead of `00:00:00.01`

3. There is an extra start time posted when the user saves in Finish Line Mode. This isn't breaking anything, but it is an unnecessary API call now that we save the Start Time the moment the user starts the timer.

4. Time Entry Time Bug (Steps to Reproduce):
- Delete all results
- Record bibs in Chute Mode
- Open Results mode
- Edit a time
- The time shows as `Na:Na:Na:Na`

### LINKED ISSUE #59: v2 Review - Assign Offline Events Bug
Steps To Reproduce:
- Create an Offline Event
- Record in Finish Line Mode without typing in any bib numbers (leave them all as 0)
- Do not record in Chute Mode
- Go to an event in the "Score & Publish Results" App Flow
- Tap "Assign Offline Event"
- Select the event you created and assign it
- You will get an unknown error

Test other Assign Offline flows (combo of bibs, etc.)

### PR DESCRIPTION
**Pull request by nathanael-rsu**
- [ ] Closes #30 
- [ ] Closes #31 
- [ ] Closes #35 
- [ ] Closes #39 
- [ ] Closes #44 
- [ ] Closes #46
- [ ] Closes #48 
- [ ] Closes #50 
- [ ] Closes #51 
- [ ] Closes #52 
- [ ] Closes #56 
- [ ] Closes #59

### CODE REVIEW

**Review by chelseaRSU — APPROVED** [review]
Nice job on those bug fixes!

**Review by chelseaRSU — APPROVED** [review]

**Review by chelseaRSU — APPROVED** [review]
Hey @nathanael-rsu, these changes look good.  Since I am going to be doing a lot of UI testing right now, I was wondering if you could do me a favor and whenever you push a commit just leave a short comment about what was going on/what you were seeing in the app.  That'll definitely help me in my testing. :)

**Comment by nathanael-rsu** [comment]
> Hey @nathanael-rsu, these changes look good. Since I am going to be doing a lot of UI testing right now, I was wondering if you could do me a favor and whenever you push a commit just leave a short comment about what was going on/what you were seeing in the app. That'll definitely help me in my testing. :)

Okay, will do. Thanks.

**Review by chelseaRSU — APPROVED** [review]

**Review by chelseaRSU — APPROVED** [review]

File: src/screens/FinishLineMode.tsx [hunk 1]
```diff
@@ -80,6 +81,21 @@ export default function FinishLineModeScreen({ navigation }: Props): React.React
 	const [loading, setLoading] = useState(true);
 	const isUnmounted = useRef(false);
 	const flatListRef = useRef<FlatList>(null);
+	const deviceType = useRef<"Phone"|"Tablet">("Phone");
+
+	// Get Device Type
+	useEffect(() => {
+		const getDeviceType = async (): Promise<void> => {
+			const type = await Device.getDeviceTypeAsync();
+			if (type === 1) {
```
Comment (chelseaRSU) [inline src/screens/FinishLineMode.tsx:90]: My only comment on this would be to eventually create an AppConstants file where the device types could be stored.  And then instead of "1", you could have it be 
```suggestion
			if (type === AppConstants.device_type_phone) {
```

Or something like that. Otherwise, this is working well and looks good!

**Review by chelseaRSU — APPROVED** [review]
